### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mark0802-prog** [mark0802-prog/furima_29251#9]
# URL
https://furima-29251.herokuapp.com/
# BASIC認証のuser_nameとpassword
- user_name
admin
- password
2222
# 出品者用のメールアドレスとパスワード
- email
koji@koji.com
- password
a12345
# 購入者用のメールアドレスとパスワード
- email
sample@sample.com
- password
a12345
# 購入用カード情報
- 番号
4242424242424242
- 期限
12月24年
- セキュリティコード
123

**Comment by tec-camp** [comment]
mark0802-prog さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
